package my_api.service;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import com.axisoft.alchemyj.execution.api.executor.WorkbookExecutor;
import com.axisoft.alchemyj.execution.common.exception.AlchemyjFormulaExecutionException;
import my_api.entity.Output;

public interface EndpointGroupService {

  public Output handleFunctionPoint(
      String functionPointName, String inputparameter10, WorkbookExecutor wbExecutor)
      throws AlchemyjFormulaExecutionException;
}
