package my_api;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

public class Constants {

  private Constants() {}

  public static final String ALCHEMYJ_FILE_PATH_STR_TEMPLATE = "static.%s";
  public static final String FUNCTION_POINT_SETTER_WB_NAME = "AlchemyJ_FunctionPoint";
  public static final String USER_NAME_SETTER_WB_NAME = "AlchemyJ_REST_Sec_UserName";
  public static final String AUTHORITY_LIST_SETTER_WB_NAME = "AlchemyJ_REST_Sec_Authority_List";
  public static final String AUTHORITY_JSON_KEY = "authority";
  public static final String PROJECT_ENCODING = "UTF-8";
  public static final String JSON_NODE_ADDITION_INFO = "_alchemyj_info";

  public static class AdditionalResponseStatusCode {
    private AdditionalResponseStatusCode() {}

    public static final int NORMAL = 200;
    public static final int SERVER_USER_RAISE_EXCEPTION = 502;
    public static final int SERVER_EXCEPTION = 500;
    public static final int NOT_FOUND_EXCEPTION = 404;
  }
}
