package my_api.configuration;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import java.util.Map;
import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("singleton")
@ConfigurationProperties(prefix = "alchemyj")
@Data
public class AlchemyjProperties {

  private boolean stopOnFormulaError;

  private boolean stopOnUserRaiseError;

  private boolean throwOnFormulaError;

  private boolean throwOnUserRaiseError;

  private boolean generateDebugExcel = false;

  private String debugExcelLogPath;

  private Map<String, String> applicationProps;

  private Map<String, Integer> classPoolLimits;

  private String licenseFileLocation;

  private String licenseEnvVariableName;
}
