package my_api.entity.base;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import com.axisoft.alchemyj.execution.api.entity.RestApiAdditionInfoResponse;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import my_api.Constants;

@Data
public class AlchemyjResource {

  @JsonProperty(Constants.JSON_NODE_ADDITION_INFO)
  private RestApiAdditionInfoResponse additionInfoResponse;
}
