package my_api;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AlchemyjSpringApplicationBootstrap {

  public static void main(String[] args) {
    SpringApplication.run(AlchemyjSpringApplicationBootstrap.class, args);
  }
}
