package my_api.servlet.filter;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import my_api.Constants;
import my_api.util.AdditionalInfoResponseUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.filter.OncePerRequestFilter;

@Slf4j
public class ExceptionHandlingFilter extends OncePerRequestFilter {

  @Autowired private ObjectMapper mapper;

  @Autowired private AdditionalInfoResponseUtils util;

  @Override
  protected void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
      throws ServletException, IOException {
    try {
      filterChain.doFilter(request, response);
    } catch (Exception e) {
      log.error("", e);
      response.reset();
      response.setContentType(MediaType.APPLICATION_JSON_UTF8_VALUE);
      List<String> messages = new ArrayList<>();
      messages.add("Internal Server Error");
      Map<String, Object> result = new LinkedHashMap<>();
      result.put(Constants.JSON_NODE_ADDITION_INFO, util.unexpectException(request, messages));
      response.getWriter().write(mapper.writeValueAsString(result));
      response.setStatus(HttpServletResponse.SC_OK);
    }
  }
}
