package my_api.util;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import com.axisoft.alchemyj.execution.api.executor.WorkbookExecutor;
import com.axisoft.alchemyj.execution.common.exception.AlchemyjFormulaExecutionException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import my_api.Constants;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component("authenticationUtil")
@Scope("singleton")
public class AuthenticationUtils {

  @Autowired private ObjectMapper objectMapper;

  public void cleanAuthorityInfoInWorkbook(WorkbookExecutor wbExecutor)
      throws AlchemyjFormulaExecutionException {
    wbExecutor.setSingleValToNameAddress(Constants.USER_NAME_SETTER_WB_NAME, "");
    wbExecutor.setSingleValToNameAddress(
        Constants.AUTHORITY_LIST_SETTER_WB_NAME, this.createAuthorityJsonString(new ArrayList<>()));
  }

  private String createAuthorityJsonString(List<String> authorityList)
      throws AlchemyjFormulaExecutionException {
    Map<String, List<String>> result = new LinkedHashMap<>();
    result.put(Constants.AUTHORITY_JSON_KEY, authorityList);
    try {
      return this.objectMapper.writeValueAsString(result);
    } catch (Exception e) {
      throw new AlchemyjFormulaExecutionException("Fail convert object to JSON", e);
    }
  }
}
