package my_api.service.impl;
// **********************************************************************
// Code generated by AlchemyJ Compiler.
// PLEASE DO NOT EDIT THIS FILE.
// **********************************************************************

import com.axisoft.alchemyj.execution.api.executor.WorkbookExecutor;
import com.axisoft.alchemyj.execution.api.handler.impl.obj.AlchemyjObjectOperationHandlerImpl;
import com.axisoft.alchemyj.execution.api.handler.intf.AlchemyjObjectOperationHandler;
import com.axisoft.alchemyj.execution.common.exception.AlchemyjFormulaExecutionException;
import com.fasterxml.jackson.databind.type.TypeFactory;
import my_api.entity.Output;
import my_api.service.EndpointGroupService;
import org.springframework.stereotype.Service;

@Service("endpointGroupService")
public class EndpointGroupServiceImpl implements EndpointGroupService {

  private AlchemyjObjectOperationHandler objectOperationHandler =
      new AlchemyjObjectOperationHandlerImpl();;
  private TypeFactory typeFactory = TypeFactory.defaultInstance();

  @Override
  public Output handleFunctionPoint(
      String functionPointName, String inputparameter10, WorkbookExecutor wbExecutor)
      throws AlchemyjFormulaExecutionException {
    /** Setter Selection * */
    wbExecutor.setVal("BizLogic", 0, 1, 0, 1, inputparameter10);

    /** re-evaluate * */
    wbExecutor.reEvaluate();

    /** Getter Selection */
    return objectOperationHandler.getObject(wbExecutor, Output.class);
  }
}
